### PR TITLE
Attempted port to 3.x

### PR DESCRIPTION
**Pull request by tinvaan**
Currently tested against python `3.8`. Keeps support for python `2.7` as well.

Tests can be run using `tox`

```shell
▶ tox 
GLOB sdist-make: /Users/tinvaan/env/src/dialpad/public/dialpad-python-sdk/setup.py
py27 inst-nodeps: /Users/tinvaan/env/src/dialpad/public/dialpad-python-sdk/.tox/.tmp/package/1/python-dialpad-1.7.0.zip
py27 installed: DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.,atomicwrites==1.4.0,attrs==21.2.0,backports.entry-points-selectable==1.1.0,backports.functools-lru-cache==1.6.4,bump2version==0.5.11,cached-property==1.5.2,certifi==2021.5.30,chardet==4.0.0,configparser==4.0.2,contextlib2==0.6.0.post1,coverage==5.5,distlib==0.3.2,enum34==1.1.10,filelock==3.0.12,funcsigs==1.0.2,functools32==3.2.3.post2,httpretty==0.9.7,idna==2.10,importlib-metadata==2.1.1,importlib-resources==3.3.1,Jinja2==2.11.3,jsonschema==3.2.0,MarkupSafe==1.1.1,more-itertools==5.0.0,packaging==20.9,pathlib2==2.3.6,pipenv==2021.5.29,platformdirs==2.0.2,pluggy==0.13.1,py==1.10.0,pyparsing==2.4.7,pyrsistent==0.16.1,pytest==4.6.11,pytest-sugar==0.9.4,python-dialpad==1.7.0,PyYAML==5.4.1,requests==2.26.0,scandir==1.10.0,singledispatch==3.7.0,six==1.16.0,-e git+https://github.com/jakedialpad/swagger-parser.git@13f21d59aef87b2babb28c9423183c341333a009#egg=swagger_parser,swagger-spec-validator==2.7.3,swagger-stub==0.2.1,termcolor==1.1.0,typing==3.10.0.0,urllib3==1.26.6,virtualenv==20.7.2,virtualenv-clone==0.5.6,wcwidth==0.2.5,zipp==1.2.0
py27 run-test-pre: PYTHONHASHSEED='1041109381'
py27 run-test: commands[0] | pipenv install --dev
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
Installing dependencies from Pipfile.lock (f3e4c8)...
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 1/1 — 00:00:01
py27 run-test: commands[1] | coverage run --source dialpad/ -m pipenv run pytest --disable-warnings /Users/tinvaan/env/src/dialpad/public/dialpad-python-sdk/test
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
Test session starts (platform: darwin, Python 2.7.16, pytest 4.6.11, pytest-sugar 0.9.4)
cachedir: .tox/py27/.pytest_cache
rootdir: /Users/tinvaan/env/src/dialpad/public/dialpad-python-sdk
plugins: sugar-0.9.4
collecting ... 
 test/test_resource_sanity.py ✓✓✓                                                                                                                                                        100% ██████████

Results (2.65s):
       3 passed
py27 run-test: commands[2] | coverage report
Name                                      Stmts   Miss  Cover
-------------------------------------------------------------
dialpad/__init__.py                           1      0   100%
dialpad/client.py                            78     12    85%
dialpad/resources/__init__.py                19      0   100%
dialpad/resources/blocked_number.py          11      0   100%
dialpad/resources/call.py                     5      0   100%
dialpad/resources/call_router.py             15      0   100%
dialpad/resources/callback.py                 5      0   100%
dialpad/resources/callcenter.py              12      0   100%
dialpad/resources/company.py                  5      0   100%
dialpad/resources/contact.py                 15      0   100%
dialpad/resources/department.py              11      0   100%
dialpad/resources/event_subscription.py      19      0   100%
dialpad/resources/number.py                  13      0   100%
dialpad/resources/office.py                  19      0   100%
dialpad/resources/resource.py                 9      1    89%
dialpad/resources/room.py                    27      0   100%
dialpad/resources/sms.py                      5      0   100%
dialpad/resources/stats.py                   10      0   100%
dialpad/resources/subscription.py            43      0   100%
dialpad/resources/transcript.py               5      0   100%
dialpad/resources/user.py                    36      0   100%
dialpad/resources/userdevice.py               7      0   100%
dialpad/resources/webhook.py                 13      0   100%
-------------------------------------------------------------
TOTAL                                       383     13    97%
py38 inst-nodeps: /Users/tinvaan/env/src/dialpad/public/dialpad-python-sdk/.tox/.tmp/package/1/python-dialpad-1.7.0.zip
py38 installed: atomicwrites==1.4.0,attrs==21.2.0,backports.entry-points-selectable==1.1.0,bump2version==0.5.11,cached-property==1.5.2,certifi==2021.5.30,chardet==3.0.4,coverage==5.5,distlib==0.3.2,filelock==3.0.12,httpretty==0.9.7,idna==2.10,Jinja2==2.11.3,jsonschema==3.2.0,MarkupSafe==1.1.1,more-itertools==8.8.0,packaging==20.9,pipenv==2021.5.29,platformdirs==2.2.0,pluggy==0.13.1,py==1.10.0,pyparsing==2.4.7,pyrsistent==0.16.1,pytest==4.6.11,pytest-sugar==0.9.4,python-dialpad==1.7.0,PyYAML==5.4.1,requests==2.26.0,six==1.16.0,-e git+https://github.com/jakedialpad/swagger-parser.git@13f21d59aef87b2babb28c9423183c341333a009#egg=swagger_parser,swagger-spec-validator==2.7.3,swagger-stub==0.2.1,termcolor==1.1.0,urllib3==1.26.6,virtualenv==20.7.2,virtualenv-clone==0.5.6,wcwidth==0.2.5,zipp==1.2.0
py38 run-test-pre: PYTHONHASHSEED='1041109381'
py38 run-test: commands[0] | pipenv install --dev
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
Installing dependencies from Pipfile.lock (f3e4c8)...
Ignoring backports.functools-lru-cache: markers 'python_version < "3.2"' don't match your environment
Ignoring chardet: markers 'python_version < "3"' don't match your environment
Ignoring configparser: markers 'python_version < "3"' don't match your environment
Ignoring contextlib2: markers 'python_version < "3"' don't match your environment
Ignoring funcsigs: markers 'python_version < "3"' don't match your environment
Ignoring functools32: markers 'python_version < "3"' don't match your environment
Ignoring importlib-metadata: markers 'python_version < "3.8"' don't match your environment
Ignoring more-itertools: markers 'python_version <= "2.7"' don't match your environment
Ignoring pathlib2: markers 'python_version < "3.6"' don't match your environment
Ignoring scandir: markers 'python_version < "3.5"' don't match your environment
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 11/11 — 00:00:05
py38 run-test: commands[1] | coverage run --source dialpad/ -m pipenv run pytest --disable-warnings /Users/tinvaan/env/src/dialpad/public/dialpad-python-sdk/test
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
Test session starts (platform: darwin, Python 3.8.2, pytest 4.6.11, pytest-sugar 0.9.4)
cachedir: .tox/py38/.pytest_cache
rootdir: /Users/tinvaan/env/src/dialpad/public/dialpad-python-sdk
plugins: sugar-0.9.4
collecting ... 
 test/test_resource_sanity.py ✓✓✓                                                                                                                                                        100% ██████████

Results (2.35s):
       3 passed
py38 run-test: commands[2] | coverage report
Name                                      Stmts   Miss  Cover
-------------------------------------------------------------
dialpad/__init__.py                           1      0   100%
dialpad/client.py                            97     12    88%
dialpad/resources/__init__.py                19      0   100%
dialpad/resources/blocked_number.py          11      0   100%
dialpad/resources/call.py                     5      0   100%
dialpad/resources/call_router.py             15      0   100%
dialpad/resources/callback.py                 5      0   100%
dialpad/resources/callcenter.py              12      0   100%
dialpad/resources/company.py                  5      0   100%
dialpad/resources/contact.py                 15      0   100%
dialpad/resources/department.py              11      0   100%
dialpad/resources/event_subscription.py      19      0   100%
dialpad/resources/number.py                  13      0   100%
dialpad/resources/office.py                  19      0   100%
dialpad/resources/resource.py                 9      1    89%
dialpad/resources/room.py                    27      0   100%
dialpad/resources/sms.py                      5      0   100%
dialpad/resources/stats.py                   10      0   100%
dialpad/resources/subscription.py            43      0   100%
dialpad/resources/transcript.py               5      0   100%
dialpad/resources/user.py                    36      0   100%
dialpad/resources/userdevice.py               7      0   100%
dialpad/resources/webhook.py                 13      0   100%
-------------------------------------------------------------
TOTAL                                       402     13    97%
_______________________________________________________________________________________________ summary ________________________________________________________________________________________________
  py27: commands succeeded
  py38: commands succeeded
  congratulations :)

```

### CODE REVIEW

**Comment by jakedialpad** [comment]
Looks like a solid improvement to me @tinvaan :)
I did run into some dependency shinanigans, but I addressed them over here if you want to see whether they make sense to you as well: https://github.com/dialpad/dialpad-python-sdk/pull/9
Feel free to cherry-pick that commit if those changes make sense to you as well, but other than that hiccup this looks great to me!

**Comment by tinvaan** [comment]
> Looks like a solid improvement to me @tinvaan :)
> I did run into some dependency shinanigans, but I addressed them over here if you want to see whether they make sense to you as well: #9
> Feel free to cherry-pick that commit if those changes make sense to you as well, but other than that hiccup this looks great to me!

Thank you! Let me see if I can add a bit of polish to get this shipped.

**Comment by tinvaan** [comment]
> > Looks like a solid improvement to me @tinvaan :)
> > I did run into some dependency shinanigans, but I addressed them over here if you want to see whether they make sense to you as well: #9
> > Feel free to cherry-pick that commit if those changes make sense to you as well, but other than that hiccup this looks great to me!
> 
> Thank you! Let me see if I can add a bit of polish to get this shipped.

Dropped the `requirements.txt` & `dev-requirements.txt` as it's redundant given the same info is conveyed in the `Pipfile`.
Have updated the README with instructions on running tests with `tox` as well.

Thoughts @jakedialpad ?

**Comment by jakedialpad** [comment]
Very nice!
Thanks @tinvaan, I'll merge it in and roll a release!

**Pull request merged**
